### ISSUE TITLE
Latest build (v0.20) failing

### ISSUE THREAD

**Issue by djhoese** [conda-forge/satpy-feedstock#31]
The latest build for Satpy 0.20 passed in #30 but failed when merged to master. I can't seem to get my Azure account to link properly to GitHub so I am unable to restart the builds (not sure if I'm supposed to be able to do that).

Can someone from @conda-forge/core help me?

Here is the link to the failed build: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=125949&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3

Not sure if this is something wrong with the recipe or a hiccup on the build.

**Comment by mariusvniekerk** [comment]
Restarted it

**Comment by jakirkham** [comment]
Looks like it passed and builds got uploaded. Please let us know if anything else comes up. 🙂

Closing...

**Comment by djhoese** [comment]
Thank you!!!
